DROP TABLE IF EXISTS CLOUD_GATEWAY_ROUTE;

CREATE TABLE CLOUD_GATEWAY_ROUTE
(
    ID          BIGINT(20)   NOT NULL PRIMARY KEY,
    ROUTE_ID    VARCHAR(100) NOT NULL,
    ROUTE_NAME  VARCHAR(100) NULL,
    ROUTE_ORDER INT(10)      NULL,
    PATH        VARCHAR(200) NULL,
    URL         VARCHAR(200) NULL,
    SERVICE_ID  VARCHAR(200) NULL,
    STATUS      TINYINT(2)   NOT NULL DEFAULT 0
);