spring:
  profiles:
    active: dev
  application:
    name: spring-es
  servlet:
    multipart:
      # 指定缓存目录以防止 linux 下出现 /tmp 目录被删除时找不到对应目录的问题
      location: /Files/Temp
  elasticsearch:
    rest:
      uris: https://localhost:9200
      username: elastic
      password: Ca1YfLbS7G+0_R34U+My
      connection-timeout: 5s
logging:
  config: classpath:config/logback-spring.xml
  file:
    path: /Files/Logs/Onysakura/Algorithm/spring/spring-es
server:
  port: 30002

custom:
  # 机器 id
  machine-id: 1 # 启动时通过 --custom.machine-id=2 参数指定机器 id
  # 业务 id
  business-id: 1
  jwt:
    signing-key: asdasdasd
