spring:
  profiles:
    active: dev
  application:
    name: algorithm-spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      # 指定缓存目录以防止 linux 下出现 /tmp 目录被删除时找不到对应目录的问题
      location: /Files/Temp
  jpa:
    show-sql: false # 日志打印 sql
    generate-ddl: true
    hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    open-in-view: false # 建议关闭
    properties:
      hibernate:
        jdbc:
          batch_size: 5000

  redis:
    # cluster: # 集群
    #     nodes: localhost:21000,localhost:21001,localhost:21002,localhost:21003,localhost:21004,localhost:21005
    host: 127.0.0.1 # 单体
    port: 6379
    password: 123456
logging:
  config: classpath:config/logback-spring.xml
  file:
    path: /Files/Logs/Onysakura/Algorithm/spring
server:
  port: 30001

custom:
  # 机器 id
  machine-id: 1 # 启动时通过 --custom.machine-id=2 参数指定机器 id
  # 业务 id
  business-id: 1
  jwt:
    signing-key: asdasdasd
